# Generated by Django 3.0.2 on 2020-02-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
