# Generated by Django 3.0.2 on 2020-02-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200206_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='123', max_length=30),
            preserve_default=False,
        ),
    ]
